spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=change-me-please-this-is-very-long-secret-key-1234567890
security.jwt.access-ttl-seconds=900
security.jwt.refresh-ttl-seconds=604800
security.jwt.issuer=auth-service
